<?php

namespace HuntersKingdomBundle\Repository;

/**
 * favorisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class favorisRepository extends \Doctrine\ORM\EntityRepository
{
}
