<?php

namespace HuntersKingdomBundle\Repository;

/**
 * offreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class offreRepository extends \Doctrine\ORM\EntityRepository
{
}
