<?php

namespace HuntersKingdomBundle\Repository;

/**
 * overwatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class overwatchRepository extends \Doctrine\ORM\EntityRepository
{
}
