<?php

namespace HuntersKingdomBundle\Repository;

/**
 * reportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reportRepository extends \Doctrine\ORM\EntityRepository
{
}
