<?php

namespace HuntersKingdomBundle\Repository;

use HuntersKingdomBundle\Entity\thread;

/**
 * threaddetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class threaddetailRepository extends \Doctrine\ORM\EntityRepository
{

    public function getCommentByThreadId(thread $thread){
        $query = $this->createQueryBuilder('u')
            ->where('u.threadid = :id')
            ->orderBy('u.createdAt' , 'DESC')
            ->setParameter ( 'id' , $thread->getId() )
            ->getQuery();
        return $query->getResult ();
    }
}
