<?php

namespace HuntersKingdomBundle\Repository;

/**
 * threaddetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class threaddetailRepository extends \Doctrine\ORM\EntityRepository
{
}
