hunters_kingdom_personne:
    resource: "@HuntersKingdomBundle/Controller/personneController.php"
    type:     annotation

hunters_kingdom:
    resource: "@HuntersKingdomBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
