hunters_kingdom_notification:
    resource: "@HuntersKingdomBundle/Controller/notificationController.php"
    type:     annotation

hunters_kingdom_favoris:
    resource: "@HuntersKingdomBundle/Controller/favorisController.php"
    type:     annotation

hunters_kingdom_overwatch:
    resource: "@HuntersKingdomBundle/Controller/overwatchController.php"
    type:     annotation

hunters_kingdom_commande:
    resource: "@HuntersKingdomBundle/Controller/commandeController.php"
    type:     annotation

hunters_kingdom_threaddetail:
    resource: "@HuntersKingdomBundle/Controller/threaddetailController.php"
    type:     annotation

hunters_kingdom_thread:
    resource: "@HuntersKingdomBundle/Controller/threadController.php"
    type:     annotation

hunters_kingdom_users:
    resource: "@HuntersKingdomBundle/Controller/usersController.php"
    type:     annotation

hunters_kingdom_categorie:
    resource: "@HuntersKingdomBundle/Controller/categorieController.php"
    type:     annotation

hunters_kingdom_event:
    resource: "@HuntersKingdomBundle/Controller/eventController.php"
    type:     annotation

hunters_kingdom_reservation:
    resource: "@HuntersKingdomBundle/Controller/ReservationController.php"
    type:     annotation

hunters_kingdom_demande:
    resource: "@HuntersKingdomBundle/Controller/demandeController.php"
    type:     annotation
hunters_kingdom_offre:
    resource: "@HuntersKingdomBundle/Controller/offreController.php"
    type:     annotation

hunters_kingdom_product:
    resource: "@HuntersKingdomBundle/Controller/productController.php"
    type:     annotation

hunters_kingdom_personne:
    resource: "@HuntersKingdomBundle/Controller/personneController.php"
    type:     annotation


hunters_kingdom_buy:
    resource: "@HuntersKingdomBundle/Controller/buyController.php"
    type:     annotation

hunters_kingdom_sell:
    resource: "@HuntersKingdomBundle/Controller/sellController.php"
    type:     annotation

hunters_kingdom:
    resource: "@HuntersKingdomBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
